"""Generate self-contained plot_6.py files with all results embedded."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


CONFIGS = {
    "task_size": {
        "json": Path("task_size/plot_4/task_size_final_with_multihop.json"),
        "output": Path("task_size/plot_4/plot_6.py"),
        "x_values": [0.4, 0.8, 1.2, 1.6, 2.0],
        "x_label": "Average task size (Mb)",
        "output_stem": "task_size_final_with_multihop_plot6",
    },
    "uav_res": {
        "json": Path("uav_res/plot_4/uav_res_final_with_multihop.json"),
        "output": Path("uav_res/plot_4/plot_6.py"),
        "x_values": [5.0, 15.0, 25.0, 35.0, 45.0],
        "x_label": "Computing resources of UAVs (GHz)",
        "output_stem": "uav_res_final_with_multihop_plot6",
    },
    "usv_num": {
        "json": Path("USV_num/plot_4/usv_num_final_with_multihop.json"),
        "output": Path("USV_num/plot_4/plot_6.py"),
        "x_values": [10.0, 20.0, 30.0, 40.0, 50.0],
        "x_label": "The number of USVs",
        "output_stem": "usv_num_final_with_multihop_plot6",
    },
}


SCRIPT_TEMPLATE = '''"""Self-contained comparison plot with explicitly embedded final results.

Generated by tools/generate_explicit_plot6.py.  This file does not read any
experiment result folder at runtime.
"""

import json
import math

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# ================= 1. Global configuration =================
plt.rcParams["font.family"] = "serif"
plt.rcParams["font.serif"] = ["Times New Roman"]
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["ps.fonttype"] = 42
plt.rcParams["xtick.labelsize"] = 12
plt.rcParams["ytick.labelsize"] = 12
plt.rcParams["axes.labelsize"] = 14
plt.rcParams["legend.fontsize"] = 13


# ================= 2. Explicit final results =================
# Important:
# 1. All values below are the final values used by the figure.
# 2. Task completion delay is already normalized per USV.
# 3. The historical PGTO/CORA/RD UAV/USV energy scaling used by plot_5.py
#    has already been applied.  Do not divide these values again.
# 4. null is reserved for a source experiment that is not available.  The
#    current task-size data contains all five MH-RMAPPO parameter points.
json_data_str = r"""
__JSON_DATA__
"""

raw_data = json.loads(json_data_str)

METRICS = ["completion_rate", "system_time", "uav_energy", "usv_energy"]
Y_LABELS = {
    "completion_rate": "Task completion rate (%)",
    "system_time": "Task completion delay (s)",
    "uav_energy": "UAV energy consumption (J)",
    "usv_energy": "USV energy consumption (J)",
}
X_VALUES = __X_VALUES__
X_LABEL = __X_LABEL__
OUTPUT_STEM = __OUTPUT_STEM__


# ================= 3. Algorithm styles =================
ALGO_LABELS = {
    "RD": "RD",
    "02_ppo": "PPO-COPG",
    "04_TD3": "TD3-COPG",
    "05_SAC": "SAC-COPG",
    "LPPOUT": "LPPOUT",
    "CORA": "CORA",
    "PGTO": "PGTO",
    "03_all_ppo": "PPO",
    "01_lngru_ppo": "LPPO-COPG",
    "06_multihop_rmappo": "MH-RMAPPO",
}
ALGO_COLORS = {
    # Each RGB channel is 80% of the previous value (20% darker).
    "01_lngru_ppo": "#B83C2A",
    "02_ppo": "#00806C",
    "03_all_ppo": "#3E96AA",
    "04_TD3": "#30436D",
    "05_SAC": "#6A7490",
    "CORA": "#C27C66",
    "LPPOUT": "#74A79B",
    "PGTO": "#654E3A",
    "RD": "#8D7D6A",
    "06_multihop_rmappo": "#6F1857",
}
STYLE_CONFIG = {
    "01_lngru_ppo": {"marker": "o", "linestyle": "--"},
    "02_ppo": {"marker": "s", "linestyle": "--"},
    "03_all_ppo": {"marker": "^", "linestyle": "--"},
    "04_TD3": {"marker": "D", "linestyle": "--"},
    "05_SAC": {"marker": "v", "linestyle": "--"},
    "CORA": {"marker": "p", "linestyle": "--"},
    "LPPOUT": {"marker": "*", "linestyle": "--"},
    "PGTO": {"marker": "h", "linestyle": "--"},
    "RD": {"marker": "X", "linestyle": "--"},
    "06_multihop_rmappo": {"marker": "P", "linestyle": "-"},
}
ALGO_ORDER = list(ALGO_LABELS)
TARGET_ALGO = "06_multihop_rmappo"
LINE_WIDTH = 1.8
MARKER_SIZE = 8.4


# ================= 4. Plot helpers =================
def get_x_key(x_value):
    """Return the JSON key used by the explicit data object."""
    key = str(float(x_value))
    if key in raw_data[METRICS[0]]:
        return key
    compact_key = f"{float(x_value):g}"
    if compact_key in raw_data[METRICS[0]]:
        return compact_key
    raise KeyError(f"No explicit data for x={x_value}")


def plot_metric(ax, metric, sublabel):
    # Draw the new algorithm last so its solid purple line stays visible.
    draw_order = [algo for algo in ALGO_ORDER if algo != TARGET_ALGO]
    draw_order.append(TARGET_ALGO)

    for algo in draw_order:
        values = []
        for x_value in X_VALUES:
            value = raw_data[metric][get_x_key(x_value)].get(algo)
            values.append(math.nan if value is None else float(value))

        style = STYLE_CONFIG[algo]
        is_target = algo == TARGET_ALGO
        ax.plot(
            X_VALUES,
            values,
            color=ALGO_COLORS[algo],
            marker=style["marker"],
            linestyle=style["linestyle"],
            linewidth=LINE_WIDTH,
            markersize=MARKER_SIZE,
            markeredgewidth=0,
            zorder=12 if is_target else 3,
        )

    ax.set_ylabel(Y_LABELS[metric], fontsize=14)
    ax.set_xlabel(X_LABEL, fontsize=14)
    ax.set_xticks(X_VALUES)
    ax.tick_params(axis="both", labelsize=12)
    ax.grid(True, linestyle="--", alpha=0.5)
    ax.text(
        0.5,
        -0.22,
        sublabel,
        transform=ax.transAxes,
        ha="center",
        va="top",
        fontsize=16,
    )
    if metric == "completion_rate":
        ax.set_ylim(0, 100)


# ================= 5. Main plotting program =================
def plot_final():
    # The extra tenth legend entry slightly enlarges the tight bounding box.
    # A 3.6-inch canvas preserves the old plot_5 output aspect ratio.
    fig, axes = plt.subplots(1, 4, figsize=(20, 3.6))
    fig.subplots_adjust(
        wspace=0.22,
        top=0.92,
        bottom=0.25,
        left=0.05,
        right=0.98,
    )

    for axis, metric, sublabel in zip(
        axes, METRICS, ["(a)", "(b)", "(c)", "(d)"]
    ):
        plot_metric(axis, metric, sublabel)

    legend_handles = []
    for algo in ALGO_ORDER:
        style = STYLE_CONFIG[algo]
        is_target = algo == TARGET_ALGO
        legend_handles.append(
            Line2D(
                [0],
                [0],
                color=ALGO_COLORS[algo],
                marker=style["marker"],
                linestyle=style["linestyle"],
                label=ALGO_LABELS[algo],
                linewidth=LINE_WIDTH,
                markersize=MARKER_SIZE,
                markeredgewidth=0,
            )
        )

    fig.legend(
        handles=legend_handles,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.88),
        ncol=len(ALGO_ORDER),
        frameon=True,
        fontsize=14,
        columnspacing=1.5,
        handlelength=2.2,
    )
    fig.subplots_adjust(top=0.85)

    plt.savefig(
        f"{OUTPUT_STEM}.pdf",
        dpi=300,
        bbox_inches="tight",
        pad_inches=0.05,
    )
    plt.savefig(
        f"{OUTPUT_STEM}.png",
        dpi=300,
        bbox_inches="tight",
    )
    print(f"Generated {OUTPUT_STEM}.pdf and {OUTPUT_STEM}.png")
    plt.show()


if __name__ == "__main__":
    plot_final()
'''


def build_script(comparison_root: Path, name: str) -> tuple[Path, str]:
    config = CONFIGS[name]
    source_path = comparison_root / config["json"]
    output_path = comparison_root / config["output"]
    data = json.loads(source_path.read_text(encoding="utf-8"))
    json_text = json.dumps(data, ensure_ascii=False, indent=2)
    script = (
        SCRIPT_TEMPLATE.replace("__JSON_DATA__", json_text)
        .replace("__X_VALUES__", repr(config["x_values"]))
        .replace("__X_LABEL__", repr(config["x_label"]))
        .replace("__OUTPUT_STEM__", repr(config["output_stem"]))
    )
    return output_path, script


def generate(comparison_root: Path, name: str) -> Path:
    output_path, script = build_script(comparison_root, name)
    output_path.write_text(script, encoding="utf-8", newline="\n")
    print(f"WROTE {output_path}")
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--comparison-root", required=True, type=Path)
    parser.add_argument(
        "--groups",
        nargs="+",
        choices=sorted(CONFIGS),
        default=sorted(CONFIGS),
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Check that every plot_6.py exactly matches its explicit source JSON",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.comparison_root.resolve()
    for name in args.groups:
        if args.validate_only:
            output_path, expected = build_script(root, name)
            actual = output_path.read_text(encoding="utf-8")
            if actual != expected:
                print(f"MISMATCH {output_path}")
                return 1
            compile(actual, str(output_path), "exec")
            print(f"VALID {output_path}")
        else:
            generate(root, name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
